"""
routes/reports.py
------------------
Export a Business Analysis Report (latest prediction + recommendations)
as PDF (ReportLab) or Excel (OpenPyXL).
"""

import os
from datetime import datetime
from flask import Blueprint, render_template, session, send_file, flash, redirect, url_for

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill

from database.models import Prediction, BusinessPlan
from routes.auth import login_required
from routes.prediction import build_recommendations
from config import Config

reports_bp = Blueprint("reports", __name__)


@reports_bp.route("/reports")
@login_required
def reports_home():
    user_id = session["user_id"]
    predictions = (
        Prediction.query.filter_by(user_id=user_id)
        .order_by(Prediction.created_at.desc())
        .all()
    )
    plans = (
        BusinessPlan.query.filter_by(user_id=user_id)
        .order_by(BusinessPlan.created_at.desc())
        .all()
    )
    return render_template("reports.html", predictions=predictions, plans=plans)


def _get_latest_prediction_or_none(user_id):
    return (
        Prediction.query.filter_by(user_id=user_id)
        .order_by(Prediction.created_at.desc())
        .first()
    )


@reports_bp.route("/reports/pdf")
@login_required
def export_pdf():
    user_id = session["user_id"]
    prediction = _get_latest_prediction_or_none(user_id)

    if prediction is None:
        flash("No prediction found yet. Please run a Risk Prediction first.", "warning")
        return redirect(url_for("prediction.prediction_page"))

    os.makedirs(Config.REPORTS_DIR, exist_ok=True)
    filename = f"business_report_{user_id}_{int(datetime.utcnow().timestamp())}.pdf"
    filepath = os.path.join(Config.REPORTS_DIR, filename)

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("TitleStyle", parent=styles["Title"], fontSize=18)
    heading_style = ParagraphStyle("HeadingStyle", parent=styles["Heading2"], spaceBefore=12)
    normal_style = styles["Normal"]

    doc = SimpleDocTemplate(filepath, pagesize=A4,
                             leftMargin=2*cm, rightMargin=2*cm, topMargin=2*cm, bottomMargin=2*cm)
    story = []

    story.append(Paragraph("Business Analysis Report", title_style))
    story.append(Paragraph(f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M')} UTC", normal_style))
    story.append(Spacer(1, 12))

    story.append(Paragraph("Business Details", heading_style))
    details_table_data = [
        ["Business Type", prediction.business_type],
        ["Investment", f"₹{prediction.investment:,.2f}"],
        ["Market Demand", prediction.market_demand],
        ["Competition", prediction.competition],
        ["Founder Experience", prediction.experience],
        ["Operating Cost", f"₹{prediction.operating_cost:,.2f}"],
        ["Target Market Size", prediction.target_market_size],
    ]
    table = Table(details_table_data, colWidths=[6*cm, 8*cm])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f0f0f0")),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(table)
    story.append(Spacer(1, 12))

    story.append(Paragraph("ML Risk Prediction", heading_style))
    story.append(Paragraph(f"<b>Predicted Risk Level:</b> {prediction.predicted_risk}", normal_style))
    story.append(Paragraph(
        "Note: This prediction is generated by a machine-learning model trained on a "
        "synthetic academic dataset and is not a guaranteed real-world outcome.",
        normal_style
    ))
    story.append(Spacer(1, 12))

    story.append(Paragraph("Recommendations", heading_style))
    form_data = {
        "competition": prediction.competition,
        "experience": prediction.experience,
        "market_demand": prediction.market_demand,
    }
    recommendations = build_recommendations(prediction.predicted_risk, form_data)
    for i, rec in enumerate(recommendations, 1):
        story.append(Paragraph(f"{i}. {rec}", normal_style))

    doc.build(story)

    return send_file(filepath, as_attachment=True, download_name=filename)


@reports_bp.route("/reports/excel")
@login_required
def export_excel():
    user_id = session["user_id"]
    predictions = (
        Prediction.query.filter_by(user_id=user_id)
        .order_by(Prediction.created_at.desc())
        .all()
    )

    if not predictions:
        flash("No predictions found yet. Please run a Risk Prediction first.", "warning")
        return redirect(url_for("prediction.prediction_page"))

    os.makedirs(Config.REPORTS_DIR, exist_ok=True)
    filename = f"predictions_{user_id}_{int(datetime.utcnow().timestamp())}.xlsx"
    filepath = os.path.join(Config.REPORTS_DIR, filename)

    wb = Workbook()
    ws = wb.active
    ws.title = "Risk Predictions"

    headers = ["Date", "Business Type", "Investment", "Market Demand", "Competition",
               "Experience", "Operating Cost", "Target Market", "Predicted Risk"]
    ws.append(headers)
    header_fill = PatternFill(start_color="4472C4", end_color="4472C4", fill_type="solid")
    for cell in ws[1]:
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = header_fill

    for p in predictions:
        ws.append([
            p.created_at.strftime("%Y-%m-%d %H:%M"), p.business_type, p.investment,
            p.market_demand, p.competition, p.experience, p.operating_cost,
            p.target_market_size, p.predicted_risk,
        ])

    for col in ws.columns:
        max_length = max(len(str(cell.value)) for cell in col if cell.value is not None) if col else 10
        ws.column_dimensions[col[0].column_letter].width = max(12, min(max_length + 2, 40))

    wb.save(filepath)

    return send_file(filepath, as_attachment=True, download_name=filename)
